[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    --html=reports/html/report.html
    --self-contained-html
    -s
markers =
    smoke: Smoke-тесты критического функционала
    regression: Регрессионные тесты основного функционала
    ui: Тесты валидации UI-элементов
