[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    -s
    --alluredir=reports/allure-results
    --clean-alluredir
markers =
    smoke: Smoke-тесты критического функционала
    regression: Регрессионные тесты основного функционала
    ui: Тесты валидации UI-элементов
    slow: Медленные тесты с ожиданием (Dynamic Properties, Timer Alerts)
